# Generated by Django 3.1.4 on 2021-01-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210113_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=30)),
                ('Nationality', models.CharField(max_length=30)),
                ('Freelance', models.CharField(max_length=30)),
                ('Address', models.TextField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Skype', models.CharField(max_length=30)),
                ('langages', models.CharField(max_length=30)),
            ],
        ),
    ]
